name: Deploy ðŸ•Šï¸

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      secrets_txt:
        description: "Paste secrets here (format: KEY=VALUE)"
        required: false

jobs:
  build_and_deploy:
    name: Build & Deploy ðŸš€
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7

      - name: Import secrets
        env:
          SECRETS_CONTEXT: ${{ toJSON(secrets) }}
        run: |
          # Get keys from .env.example
          if [ -f .env.example ]; then
            # Extract keys from .env.example, ignoring comments and empty lines
            grep -v '^#' .env.example | grep -v '^$' | while IFS='=' read -r key value; do
              # Trim whitespace from key
              key=$(echo "$key" | xargs)
              if [ -n "$key" ]; then
                # Get secret value using jq
                secret_value=$(echo "$SECRETS_CONTEXT" | jq -r ".[\"$key\"]")
                if [ "$secret_value" != "null" ] && [ -n "$secret_value" ]; then
                  echo "$key=$secret_value" >> $GITHUB_ENV
                fi
              fi
            done
          fi

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install || (bun install && git add bun.lockb && git commit -m "chore: update bun.lockb" && git push)

      - name: Build project
        run: bun run build && touch ./dist/.nojekyll


      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: public
          folder: dist  # âš¡ Adjust to your build output folder (dist or out)
